# Generated by Django 3.2 on 2021-04-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='solution',
            field=models.CharField(default='', max_length=50),
        ),
    ]
