# Generated by Django 3.2 on 2021-04-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_data_pcr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='pcr',
        ),
    ]
