# Generated by Django 3.2 on 2021-04-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_remove_data_pcr'),
    ]

    operations = [
        migrations.CreateModel(
            name='pcr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcr_name', models.CharField(max_length=45)),
                ('pcr_year', models.CharField(max_length=45)),
                ('pcr_dept', models.CharField(max_length=45)),
                ('pcr_div', models.CharField(max_length=45)),
            ],
        ),
    ]
