# Generated by Django 3.2 on 2021-04-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0005_pcr'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcr',
            name='pcr_votecount',
            field=models.IntegerField(default=0),
        ),
    ]
