# Generated by Django 3.2 on 2021-05-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0008_auto_20210505_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='user_vc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
