# Generated by Django 3.2 on 2021-05-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0009_data_user_vc'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='dept_vc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
