# Generated by Django 3.2 on 2021-05-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0010_data_dept_vc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='vc_dept_head_ans',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
