# Generated by Django 3.2 on 2021-05-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0012_auto_20210508_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='final_dept',
        ),
        migrations.AddField(
            model_name='data',
            name='all_cr_vc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
