# Generated by Django 3.2 on 2021-06-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0013_auto_20210508_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_login_id', models.CharField(blank=True, max_length=45, null=True)),
                ('hod_password', models.CharField(blank=True, max_length=45, null=True)),
                ('dept', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
